### ISSUE TITLE
能加入下载所在专辑图片，mp3 tag等信息吗？

### ISSUE THREAD

**Issue by i0sdev** [sk1418/zhuaxia#13]
如题

**Comment by sk1418** [comment]
这个功能已经有了呀. 在你那不工作吗? 我刚刚测试了下163的, 封面和tags正常. xiami没试

**Comment by i0sdev** [comment]
下载后拖到 iTunes里好像没有。

**Comment by sk1418** [comment]
我没有itunes， 我看的下载的mp3的meta data，里面有信息。 封面也抓下来保存成图了。 xiami的还有专辑介绍。 你用个别的播放器看下有没有。如果确实没写上，发给我专辑链接我测试下。

**Comment by i0sdev** [comment]
以这个为例 http://music.163.com/#/playlist?id=4332341, 这个下载了文字信息都有，但是专辑封面没有。
再比如 这个歌单http://music.163.com/#/playlist?id=42626737 里的 http://music.163.com/song?id=229289，http://music.163.com/song?id=27698144，等等歌曲，专辑封面没有，mp3的文字信息有的。

其他的歌单、专辑里都有类似的情况，文字有，封面不全。

**Comment by sk1418** [comment]
你issue题目是: `能加入下载所在专辑...`

我看了一下, 你的例子都不是"专辑", 而是用户自己建的歌单. 这种歌单, 没实现抓封面图的功能. 关于封面和专辑介绍:(仅限**专辑**)

xiami: 封面 + 文字介绍
163: 封面

对于用户自己创建的歌单(163)/精选集(xm) 没下载封面, 因为觉得没什么意义
