### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by N00D13** [sk1418/zhuaxia#14]
I like your software, but for an Germany Guy it is i little bit tricky to use your software.

**Comment by sk1418** [comment]
Okay, ich kann ueberlegen, eine Englisch Uebersetzung zu bauen. Ich dachte dass xiami.com oder music.163.com sie nur Chinese Seite haben.  Wenn Du socher Website nicht lesen kannst, funktioniert meine Applikation soweiso nicht, oder? ^_^

**Comment by N00D13** [comment]
Hahah, i use a translator for the website.
I use your software and it's awesome but the configuration is hard for me :smile:

**Comment by sk1418** [comment]
I see, I am gonna provide an english screen output/log/config etc. when I
got time.

**Comment by N00D13** [comment]
thx!

**Comment by sk1418** [comment]
I am working on the translation. btw, in configuration file there are already both english and chinese comments.

**Comment by sk1418** [comment]
@N00D13  pushed english translation to "bleeding" branch.  you can test if you like. I didn't think about the translation seriously. therefore there could be some typoes, bad translations etc. Or some functions don't work any longer... just open issues if you find anything.   after about 3,5 days I am gonna merge the bleeding into master.

**Comment by pangxiaoxi** [comment]
zhuxia has closed！ 




xiaoxi.pang@gmail.com

From: Kai Yuan
Date: 2015-08-07 05:17
To: sk1418/zhuaxia
Subject: Re: [zhuaxia] Translation (#14)
@N00D13 pushed english translation to "bleeding" branch. you can test if you like. I didn't think about the translation seriously. therefore there could be some typoes, bad translations etc. Or some functions don't work any longer... just open issues if you find anything. after about 3,5 days I am gonna merge the bleeding into master.

**Comment by pickfire** [comment]
@sk1418 Why is the README partially translated? 就像现在，一点中文、一点英文, 一塌糊涂. I suggest to use an chinese only version with an english translated page link at the top of the page.

**Comment by sk1418** [comment]
@pickfire  我不明白你的意思, 怎么叫partially?你是说那几个标题还是英语? 比如screenshot, introduction... ? 这无所谓吧?  剩下的都是中文吧? 怎么叫一点中文? 我觉得到不了一塌糊涂地步呀... :-(

**Comment by pickfire** [comment]
@sk1418 我的意思是，要就全部中文（包括标题），要就全部英文。这比较容易看。不是吗？

**Comment by sk1418** [comment]
@pickfire 
我的md目录是自己脚本生成的, 中文标题会有问题. 也就懒了没弄. 
我觉得标题英文影响也不大吧, 就那么几个字, 而且天天到处都能见到的.  要让中文版没有英文词儿, 我觉得也挺难做到的.
这个不打算去修改了. 如果你有兴趣可以修改我的目录生成脚本, 让它支持中文标题.

**Comment by pickfire** [comment]
@sk1418 我也倒是不觉得什么，没兴趣修改。:P
