### ISSUE TITLE
How to Download in 320kbits?

### ISSUE THREAD

**Issue by N00D13** [sk1418/zhuaxia#15]
I add my Username and Password to the Config File but how can i Download Music in 320kbits?

**Comment by sk1418** [comment]
from which website you want to pull 320kbps resources? xiami? or 163? please give at least one example link, and tell what do you expect, what you got, Stacktrace, if there are.  

If you try to download 320kbps music from xiami.com, you have to pay, and become the vip user.

**Comment by N00D13** [comment]
I Download them from 163.

**Comment by sk1418** [comment]
@N00D13  Not all songs from 163 have HQ resource. However I have to check the json responsed by the server. pls give one example link.

**Comment by N00D13** [comment]
http://music.163.com/#/album?id=412890

**Comment by sk1418** [comment]
@N00D13  I tested your link. The album could be downloaded in 320kbps quality. Perhaps you cannot read the Chinese README/help, you should add `-H` option  for 320kbps, and for 163, you don't have to login to download 320kbps songs. Now English translations of README/Help doc have been merged into master.
