### ISSUE TITLE
不能下载热门全部50首

### ISSUE THREAD

**Issue by i0sdev** [sk1418/zhuaxia#16]
看了下`zhuaxia.conf`,说只能最多30？怎么下载全部50首呢？记得之前设置成50，可以下载50的。能不能设置成`0`就是无限制？

**Comment by sk1418** [comment]
我当时记不得为什么要做这个设置了。 可能原因有两个， 一个是在没加入网易功能前，好像xiami返回的json就fix的30项，里面还有奇怪的项目。 现在我这访问xiami很麻烦， 就没再测试。 另一个是， 如果太多，可能造成服务器ban。 这个后来加入了一个试验性选项， 动态选择代理。  至于这个30，是写死的， 如果你想测试， 可以修改这行：https://github.com/sk1418/zhuaxia/blob/master/zhuaxia/config.py#L53  不知能不能暂时解决你的问题。

**Comment by i0sdev** [comment]
后来通过源代码里查找关键字 `30`，找到这个，改了下，重新安装了下就可以。

当然，如果能`config`里设置`= 0`代表**下载所有项目**就好了。这可能要动源代码了。

**Comment by sk1418** [comment]
@i0sdev  你改了以后，多线程下载50首，没有被服务器ban的情况吗？ 按你说的修改这个其实很容易。只是不记得当初为什么弄这个30了。 回头我查下commit看是不是记录了。 如果你测试了50没问题。 我就修改下

**Comment by i0sdev** [comment]
我是在国内，设置成50，目前看好像没有被服务器ban，可能下的次数不多。当然如果能命令时像 `zx -0 url`代表无限制，`zx -21 url`自定义现在数量就好了。

没有虾米账号，试了下，随便首页找了链接，`http://www.xiami.com/album/218624543?spm=a1z1s.6843761.1110925389.12.1P5d4T`说不能识别的url
`

**Comment by sk1418** [comment]
我争取近期修改下这个.
另外想办法挂代理测试下你说的xiami的情况,很长时间没测试xiami,不知道他们的api有没有变化.

**Comment by sk1418** [comment]
@i0sdev  我修改了关于下载热门歌曲数量的部分。 现在如果在配置文件中设置一个`<=0`的值， 将下载所有的热门歌曲。

关于xiami， 你给的链接是一个专辑链接。我测试了下， 可以下载，并没有你说的问题。你是不是没用引号把链接扩起来？ 但是解析过程中beautifulsoup会输出一段warning。 我也做了相应修改， 只是让beautifulsoup不输出警告了。

**所有上述变更已push到bleeding branch， 2,3日后如无新问题， 会merge到master**

你可以测试一下。 谢谢

**Comment by i0sdev** [comment]
我之前一直都是 `zx url（网易音乐）`，没有用括号，用起来倒没问题。

不知道怎么升级，只能重新 git clone 再安装。
----
### 虾米
上面的链接下载可以了，但是关于 BeautifulSoup 有警告的:
```
/Library/Python/2.7/site-packages/beautifulsoup4-4.4.1-py2.7.egg/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")
```

可是，找了其他歌手的链接，比如`http://www.xiami.com/artist/1260?spm=a1z1s.6659509.226669510.9.Q25ATF&from=search_popup_artist`, 就说链接不能识别。一开始以为是url里面？后面的部分影响，删掉后还是不能识别。

试了下专辑`http://www.xiami.com/album/1029065888?spm=0.0.0.0.qgxs6h`, 除了BeautifulSoup的警告外，下载正常。

### 网易音乐
运行正常。

----

试了下设置成 `0`，虾米和网易都可以下载全部。

还有就是，老是有这个警告
```
Warning: Cannot load config [lang], use default value: CN
WARNING: [虾] 不登录虾米进行下载, 虾米资源质量为128kbps.
```

**Comment by sk1418** [comment]
@i0sdev 

- 用引号引用命令行参数是good practice, 不是用括号. 比如: `command "foo" "bar" "http://whatever"`
- 我在bleeding branch里对于beautifulsoup做了一些改动, 我本地测试不出警告了
- 至于xiami 歌手的链接, 我只能等下班回家测试下,再反馈结果
- 如果是archlinux就更新zhuaxia-git包就可以了. 如果是其它发行版, 只能重新安装了.
- `Warning: Cannot load config [lang], use default value: CN` 这个是因为上次升级添加了中英语言选项, 在你的配置文件添加`lang=en|cn` 应该就没有警告了. 这个在README里有写.
- `WARNING: [虾] 不登录虾米进行下载, 虾米资源质量为128kbps.` 这个是因为用户没给出正确的xiami登录信息. 可以考虑修改, 显示这个警告, 只当下载项目有xiami资源时.

**Comment by i0sdev** [comment]
- 不好意思，括号是我的笔误。
- `-b bleeding --single-branch` 重新安装后，试了下，虾米的出错：`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`。网易的正常。
- 看上去网易的`url`友好点儿，虾米的`url`里包含太多多余的信息。 
- 我用的Mac，看上去只能重新 clone 再安装了。对了，能加入到 pip 么？
- 设置了 cn，好了。
- 嗯，有道理。

**Comment by sk1418** [comment]
1. beautifulsoup 的warning 又做了些调整
1. xiami的艺人热门已修复， 因为xiami网修改了链接格式。已经做了多种（3种）链接判断
1. 如果测试的话， clone一次pull就可以了，然后在working copy里测试，没问题再安装
1. xiami object做了lazy initialization, 也就是需要的时候才初始化，这样那个警告也就只有xiami资源的时候才显示
1. 上述改动已push到了bleeding， 请你测试下， 如无其它问题， 过2,3天会进master

**Comment by i0sdev** [comment]
1. ok 了。
2. 热门歌曲，在虾米和网易测试，我这里的结果是**只有列表里第一个歌曲**被探测到并下载。（其实热门20首足矣，我还嫌多了点，每个人Top10就行，所以我也赞同你的爬热门页没必要）
3/4/5 ok

**Comment by sk1418** [comment]
@i0sdev  关于2, 我这里是xiami下载第一页20首, 网易下载50, (如果你配置文件设置了0, -1 或者大于50的数). 我昨天修改完测试时,也是有你说的只一首问题. 后来发现, 用的是已安装的zhuaxia,而不是开发目录的....  可能你也是同样情况吧,如果你clone了一个单独的目录, 切换到bleeding后, 得`./zx ...`, 测试, 不能`zx ...` 测试, 否则你之前安装的zx将被采用, 如果你的配置文件topN设置的0或-1, 就只有1首会被下载. 因为bleeding中新的改动根本没被采用. 你看下是不是这个原因.

**Comment by i0sdev** [comment]
1. 刚才我是直接 `clone` 的 `bleeding` 分支，然后 `setup` 覆盖安装。现在把老的删了，重新安装的 `bleeding` 分支，再用 `zx` 运行。你说的切换，用 `./zx ...` 不会用😫。
2. 结果是，设置`0`，虾米和网易的热门歌曲还是各只下1首；设置`-1`，下载正常虾米20，网易50。专辑下载，设置`0`，没出现问题，正常，都是全部下载。
3. 删除程序是把这两个地方`/usr/local/bin/zx`，`~/.zhuanxia/zhuaxia.conf`都删掉就可以吗？

**Comment by sk1418** [comment]
1. 我意思就是clone一份, 然后不用安装, 在clone的目录里运行当前的zx, 而不是你安装的. 这个无关紧要的
1. 那个topN的配置文件选项(0,-1,...) 只针对艺人热门,与专辑什么的无关. 昨天测试是可以下载不止一首的.  我待会再拿163测试下看看, 再反馈
1. 是的, 对于xiami就是艺人热门歌曲里的第一页的歌曲下载
1. 一般来说不用删除. 特别是你自己的`$HOME/.zhuaxia`里的内容, 不应该删除, log除外,如果你觉得log太多了,可以删log文件. 当然, 如果你删除了配置文件,下次运行会自动生成一个全是默认值的. 还有一个就是随着程序更新,也许有新功能需要新的选项, 例如上次那个lang=..., 你的本地配置没有, 就用缺省值, 会看到warning...

**Comment by sk1418** [comment]
@i0sdev 

2 的确是我修改的问题。 我只实现了如果是负数， 不做限制， 现在加上如果是`0`， 也忽略最大限制。 这次应该没问题了。

**Comment by i0sdev** [comment]
虾米和网易都测试了，专辑、热门、单曲，`topsong =`0`,`-1`,`7`，我这边现在应该没什么使用上问题，以后若发现，再提交。

谢谢你的程序！大👍！

如果能`pip install`就好了。

**Comment by sk1418** [comment]
pip 以后有空再弄。
merged into master.
