### ISSUE TITLE
能不能功能上连歌词也一块儿下载？

### ISSUE THREAD

**Issue by i0sdev** [sk1418/zhuaxia#17]
单独的同名txt或者其他文本文件，或者能嵌入到歌曲本身里吗，就像MP3那种信息。

**Comment by sk1418** [comment]
@i0sdev 

功能已实现， 已经push到bleeding branch， 加`-l` 选项可以一并下载歌词， 同时支持xiami与163

在开发跟测试的时候发现， 也许是我发了太多请求， 我的ip无法下载163的mp3了。 挂了国内代理可以。但是歌词是可以抓的。我现在不确定只是我ip被163封了还是人家封所有国外ip。

如果你有时间，请xiami和163各种不同情况，链接类别都测试一下。多谢。

如果没什么其它问题， 2,3天后进master.

**Comment by sk1418** [comment]
merged into master
