### ISSUE TITLE
downloading mp3@163 has been blocked if user's IP is out of China

### ISSUE THREAD

**Issue by sk1418** [sk1418/zhuaxia#18]
same solution for xiami could be used. 
to be fixed...

**Comment by sk1418** [comment]
zhuaxia: 

	POST /eapi/song/enhance/download/url?br=128000&id=35403523_0 HTTP/1.1
	User-Agent: android
	Accept-Encoding: gzip
	Content-Length: 1063
	Content-Type: application/x-www-form-urlencoded; charset=UTF-8
	Host: music.163.com
	Cookie: usertrack=ezq0aVUZuKcsMSuCdoO1Ag==; MUSIC_U=b81398e940591f7688194f1ed4023d8a5ca5f514effb093a520a2b5551d4ea5abd38a1b1fcf7149602350a75b870eb3afe2897047e8106fb; __csrf=14e633e4f8dd065475a0171c93b0621a; deviceId=358239058562770; appver=2.9.1; os=android; osver=4.4.2; mobilename=Nexus5; resolution=1776x1080; channel=netease
	Connection: close
	Connection: close

**Comment by Rycton** [comment]
Hello,
regarding the request posted above:
You think that including this weird "params"-parameter would return a valid response from 163?
Because posting to /eapi/song/enhance/download/url?br=128000&id=35403523_0 with all the headers from above returns an empty response for me...

**Comment by sk1418** [comment]
@Rycton  
In Short: my above comment is just a reminder for myself.  it is not the solution. 

Long story, if you were interested:

I found that the netease/163 android app can parse and download mp3 songs directly. Therefore I was trying finding out the way, to download netease mp3 without China-proxy. After monitoring the request/response packages of my android device, I captured that post request. It posted an encryped "params" to the above link, the encrypted params is very long, I didn't paste there. I've also found out the algorithm to encrypt the params even the pub-key. However without the private key, I cannot see what was encrypted. At least what parameters were posted to the server. This is important, because we should get the real, oversea downloadable mp3 url from the response. That's why you see the last two "revert" commits.

The issue is still open. It seems that the proxy server is the only way to go. Proxy implementation is on going. almost done. just needs some more test. pls wait for the next zhuaxia release. Or "watch" this repo, so that you could get informed when the implementation is pushed to "bleeding" branch.

**Comment by Rycton** [comment]
this algorithm to encrypt the params, is it mentioned here: https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%99%BB%E5%BD%95API%E5%88%86%E6%9E%90
Because if so, i might try to find out which strings were encrypted for the "params" pameter.
btw, does the "params" stay the same for each request to 163 with the same song-id or does it change? Because i noticed, that the "oversea-ip mp3 download url" expires rather fast.

**Comment by sk1418** [comment]
@Rycton  

Thanks for digging it out. In fact I've found it days ago, also I mentioned in my comment `I've also found out the algorithm to encrypt the params even the pub-key.` But this didn't help, because what I can capture is just the encrypted `params`.  If you can read chinese, you can check this out: https://github.com/darknessomi/musicbox/issues/168  I need find out what parameter they encrypted. But I am not able to carry on....

I noticed as well, that the mp3 url it responsed has a segment with timestamp string. I don't know yet how do they handle the timeout. But first thing is finding out the details of the parames.  Because the POST request will response the real mp3 url, likely we could get urls for different bit-rates. If you analyse the package the android sent out you can see it. For the expiration, I cannot test so further, however if it is necessary, we could re-POST to get the new url when a timeout occured. well, as I said, the key is the Params. 

 It would be great if you were interested in unboxing the params and contribute zhuaxia..

**Comment by Rycton** [comment]
Thanks for claryfying. Unfortunately i have no knowledge of chinese whatsoever, so i have to pass on that, but i will try to find out more about the way they "produce" the params and post my results here. Thanks again for explaining!

**Comment by sk1418** [comment]
Proxy support for both xiami.com and music.163 implemented and merged into bleeding and master
