### ISSUE TITLE
可以增量下载吗

### ISSUE THREAD

**Issue by lianxiangru** [sk1418/zhuaxia#20]
比如我已经下载了我喜欢的歌单，过一段时间想更新一下，能只下载没下载过的歌曲吗。本地存一个已下载的musicid列表应该还比较好实现。。

**Comment by sk1418** [comment]
incremental downloading (activated by option `-i` ) is working in bleeding branch.

To do:

- [ ] more tests needed
- [ ] [Performance] build hist_list of skipped songs by filtering for later (finish hook) use
- [ ] empty history data option (`-d`) and function impl.
- [ ] export all history data to csv option (`-e`) and function impl.
- [ ] show/saveToFile summary function
- [ ] build finish hook function for ( quit/show summary/save ) summary
- [ ] better help output?
- [ ] readme, changelog, version(3.0?)

@lianxiangru  the simple incremental downloading should work in bleeding branch, however as you see, there are some more features still in todo list. You can test if you like.

**Comment by lianxiangru** [comment]
@sk1418 Great! Thanks for your work!

**Comment by sk1418** [comment]
@lianxiangru 
除了readme, changelog, version 的改动(done in dev branch)没merge到bleeding, 剩下的todo都已经完成并merge到bleeding branch了. 只是测试比较少. 

请测试一下, 如有问题请反馈, 如无明显bug,  过2,3天我merge进master.
thanks.

**Comment by sk1418** [comment]
merged into master. issue closed..

**Comment by lianxiangru** [comment]
@sk1418 Sorry for late reply.. 明天去加拿大开会，最近太忙了。。找时间一定测试下。先谢谢你的工作了！！

**Comment by lianxiangru** [comment]
@sk1418 今天用zhuaxia备份了下歌曲。没有什么问题。

不过现在海外貌似只能挂代理了。readme里说的不checkip的服务器似乎失效了。

**Comment by sk1418** [comment]
是的, 目前看中国代理是必须的了.
