### ISSUE TITLE
有些音乐没有下载完整

### ISSUE THREAD

**Issue by lianxiangru** [sk1418/zhuaxia#23]
如图
![screenshot from 2015-11-17 01-33-12](https://cloud.githubusercontent.com/assets/8991941/11204281/34abf8e2-8ccb-11e5-86cf-f0c6cfea68dd.png)
不知道具体原因是什么。。断线重连的时候没有覆盖原文件？

**Comment by sk1418** [comment]
应该属于#21的问题, 关闭这个, 一并放到那边了.
