### ISSUE TITLE
Line 134 in netease.py : AttributeError: 'module' object has no attribute 'download_by_url'

### ISSUE THREAD

**Issue by notthesame23** [sk1418/zhuaxia#24]
Hi,

I think I've found a small error. I'm on OSX 10.10.5.

At least for me changing line 134 in netease.py to this, seems to help with the object has no attribute error, when downloading albums from netease music:

 downloader.download_url(self.logo, path.join(d,'cover.' +self.logo.split('.')[-1]))

OLD VERSION was this:
 downloader.download_by_url(self.logo, path.join(d,'cover.' +self.logo.split('.')[-1]))

Thanks for providing this great tool.

**Comment by sk1418** [comment]
@notthesame23  yes, it is a bug from refactory.. Thank you for point it out. fixed in master & bleeding branch.
