### ISSUE TITLE
error using proxy option

### ISSUE THREAD

**Issue by rinaldi6109** [sk1418/zhuaxia#28]
I've used in the past your script which worked like a charm. Today I found that it does not work anymore outside China, so I've updated the configuration file but running the script yields the output in the attached image, for just a second. Then standard output fills the screen but doing nothing.
![proxy](https://cloud.githubusercontent.com/assets/1431515/12558915/7e87acec-c392-11e5-8df6-4fec31754181.png)

**Comment by sk1418** [comment]
from my testing, China proxy is required to download resources from 163.com or xiami.com. how did you setup the proxy setting in `zhuaxia.conf`?  Instead of  making screenshots, you could set the logfile level to Debug and then read the log file for more details.

**Comment by rinaldi6109** [comment]
I modified the config file following your instructions. 
I made a screenshot since the screen with red lines appears for just a second and then disappears!
Anyway, after changing the log level from INFO to DEBUG in the config file, I have collected the log file and I have attached it here. Can it be useful to understand which is the problem?

**Comment by sk1418** [comment]
I cannot see the attached file/log info. You can paste the proxy you used and also the link you were trying to download. it would be good also with log. Then I can do the same test and try to reproduce your problem.

**Comment by rinaldi6109** [comment]
Sorry, I've recognized that log files are not supported as attachment. Now it shouldn't be any problem since I have created a zip file
[zhuaxia.zip](https://github.com/sk1418/zhuaxia/files/103855/zhuaxia.zip)
.

**Comment by rinaldi6109** [comment]
from my config file: 
china.proxy.http=114.219.223.19:8080
I'm using your script on a ubuntu 14.4 pc.

**Comment by sk1418** [comment]
I tested with your proxy and dl link, it didn't work. It is the problem of you proxy. I just picked another proxy server, for example: `120.26.77.11:80`, your songs could be downloaded with latest zhuaxia. (v3.0.3). Please try with different proxy server. If it worked, please report or close the issue. Thank you for testing zhuaxia.

**Comment by rinaldi6109** [comment]
Same error even with your proxy. 
Can you telle me how can I update my zhuaxia installation to 3.0.3 version, under ubuntu? Thanks for your patience.

**Comment by sk1418** [comment]
I don't use ubuntu. How did you install zhuaxia? In fact you don't have to "install" it, it is a python program. You can clone/download the source codes and start zhuaxia. If you want to install the python package, there is a section in README.

**Comment by rinaldi6109** [comment]
Upgrading to v3.0.3 (it suffices to copy all the files in the zip archive and repeat the installation procedure described in the readme file) has solved the issue.
Thank you!
