### ISSUE TITLE
虾米账户登录失败

### ISSUE THREAD

**Issue by daozen** [sk1418/zhuaxia#31]
提示如下，我的python版本为2.7.10，不知道是否有影响？谢谢

zx -H "http://www.xiami.com/album/2100185160?spm=a1z1s.6659509.6856557.9.dnLAxE"
[虾] 登录虾米...
/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
WARNING: [虾] 登录失败, 略过登录, 虾米资源质量为 128kbps.

**Comment by daozen** [comment]
发现了问题所在，因为我的账户绑定了支付宝，所以原来的登录方式登录不进去了

**Comment by sk1418** [comment]
好久没测试xiami登录了, 因为我反正没有那种vip账户, 下载也就是128kbps, 登录其实没什么必要了. 
至于支付宝什么的, 更不太懂了, 我刚刚才开了一个国内银行账户和支付宝账户, 还不知道具体怎么用呢.  :-\
