### ISSUE TITLE
网易不能下载了

### ISSUE THREAD

**Issue by S1U** [sk1418/zhuaxia#32]
试了几个
http://music.163.com/#/playlist?id=318581326
http://music.163.com/#/song?id=167802

能获取列表，但显示失败的任务，都是✘，没有具体的出错信息。

---
虾米OK

**Comment by sk1418** [comment]
恩,刚测试了下, netease服务器那边又改了api, 获取真实链接的方法改了, 我抽空抓紧fix了它...

**Comment by sk1418** [comment]
@S1U  已根据163的变动做了相应更改. 你的两个链接均可以下载.

- 因为163的新变动, 现在依赖多了一个pycrypto
- 每个163的歌曲现在解析比以前多了2次requests(一次加密后post, 一次get), 所以一次解析大量歌曲的时候会比以前慢, 当然也可能是我这里挂中国代理速度影响的原因.  目前还没有用户可以看到的解析进度, 这个如果有需要可以加上, 也就是真正链接在正式开始下载前再做解析, 也许可以user friendly一些

你可以测试一下, 有问题再反馈.

**Comment by S1U** [comment]
ok 了 :+1:
