### ISSUE TITLE
downloaded mp3 files are saved with the same name

### ISSUE THREAD

**Issue by L2501** [sk1418/zhuaxia#37]
when downloading from full album links xiami all tracks are saved with same name

zx 'http://www.xiami.com/album/2100252256'

all tracks > H△G_Everlasting Night of Teenage Girls.mp3

**Comment by sk1418** [comment]
你中国的吧, 我这打不开你那个链接, 挂中国代理后, 每次都访问受限, 要输入验证码, 尽管输对了还是要没完没了重输. 页面里什么内容. 很久没试xiami了, 不知道他们又搞了什么东西..

**Comment by hailinzeng** [comment]
下载专辑的时候，歌曲的名字获取错误。json中的'title'字段现在xiami返回的都是专辑名。需要改成'name'或者'songName'字段。参考我发的pull request #46 。

**Comment by sk1418** [comment]
I think this issue can be closed, right?
