### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by kobemtl** [sk1418/zhuaxia#38]
Got the error message below if china.proxy.http set. Please help.謝謝了.

**SYSTEM INFO**
> ~$ zx -v
zhuaxia (抓虾) 3.1.0
~$ python -V
Python 2.7.6
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
~$ uname -a
Linux homeserver 4.2.5-040205-generic #201510270124 SMP Tue Oct 27 01:25:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**ERROR MESSAGE**

> ~$ zx "http://music.163.com/#/song?id=410846246"
Traceback (most recent call last):
  File "/usr/local/bin/zx", line 5, in <module>
    pkg_resources.run_script('zhuaxia==3.1.0', 'zx')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-3.1.0-py2.7.egg/EGG-INFO/scripts/zx", line 122, in <module>
    commander.shall_I_begin(option)
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-3.1.0-py2.7.egg/zhuaxia/commander.py", line 70, in shall_I_begin
    from_url_163(m163, option.inUrl)
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-3.1.0-py2.7.egg/zhuaxia/commander.py", line 106, in from_url_163
    song =netease.NeteaseSong(m163,url=url)
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-3.1.0-py2.7.egg/zhuaxia/netease.py", line 60, in __init__
    j = self.handler.read_link(url_song % (self.song_id,self.song_id)).json()['songs'][0]
  File "/usr/local/lib/python2.7/dist-packages/zhuaxia-3.1.0-py2.7.egg/zhuaxia/netease.py", line 243, in read_link
    retVal =  requests.get(link, headers=self.HEADERS, proxies=requests_proxy)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 305, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 206, in get_connection
    except_on_missing_scheme(proxy)
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 636, in except_on_missing_scheme
    raise MissingSchema('Proxy URLs must have explicit schemes.')
requests.exceptions.MissingSchema: Proxy URLs must have explicit schemes.

**Comment by kobemtl** [comment]
I changed the 'http' to 'http://' in neteasy.py. Then installed again. This time no more error. But not able to download any song. Just like no proxy.

**Comment by sk1418** [comment]
I am gonna check it and give you feedback on weekend.

**Comment by kobemtl** [comment]
謝謝回复。
I was trying 網易 but not xiami. And I am sure the proxy was working since I was able to use the official client. 

Thanks again and looking forward for your answer.

**Comment by sk1418** [comment]
@kobemtl  The changes were done in **bleeding** branch. Can you please give it a try and report the result?

The given song can be downloaded here, in my test.

**Comment by kobemtl** [comment]
Thanks. But still not working.....

same error if I am not replacing all the 'http' to 'http://'. But after chaning to 'http://', still not able to download the song. 


> ~$ ~/tmp/zhuaxia/zx "http://music.163.com/#/song?id=410846246"
Traceback (most recent call last):
  File "/home/kobe/tmp/zhuaxia/zx", line 122, in <module>
    commander.shall_I_begin(option)
  File "/home/kobe/tmp/zhuaxia/zhuaxia/commander.py", line 70, in shall_I_begin
    from_url_163(m163, option.inUrl)
  File "/home/kobe/tmp/zhuaxia/zhuaxia/commander.py", line 106, in from_url_163
    song =netease.NeteaseSong(m163,url=url)
  File "/home/kobe/tmp/zhuaxia/zhuaxia/netease.py", line 60, in __init__
    response = self.handler.read_link(url_song % (self.song_id,self.song_id))
  File "/home/kobe/tmp/zhuaxia/zhuaxia/netease.py", line 251, in read_link
    retVal =  requests.get(link, headers=self.HEADERS, proxies=requests_proxy)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 305, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 206, in get_connection
    except_on_missing_scheme(proxy)
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 636, in except_on_missing_scheme
    raise MissingSchema('Proxy URLs must have explicit schemes.')
requests.exceptions.MissingSchema: Proxy URLs must have explicit schemes.

**Comment by sk1418** [comment]
I don't have this problem. which requests version do you have?

**Comment by kobemtl** [comment]
>>> requests.__version__
'2.2.1'

**Comment by sk1418** [comment]
the requests latest release is 2.1.0. pls give this version a try.

**Comment by kobemtl** [comment]
Just install 2.10.0. now just no response after executing the zx. :<

**Comment by sk1418** [comment]
what do you mean no response? what is in log file?

**Comment by kobemtl** [comment]
where and how do i check log? I am not familiar with Python.

No response means nothing happen after running zx

**Comment by kobemtl** [comment]
actually its my first time using python. please help. thanks,

**Comment by sk1418** [comment]
~/.zhuaxia/zhuaxia.log

**Comment by sk1418** [comment]
but it is quite late here, I would check it tomorrow... as I said, with the same url, it worked here, with proxy.

**Comment by kobemtl** [comment]
I see. thank you so much for your help. I will keep trying and let you know. ttyl

**Comment by kobemtl** [comment]
here is the log.

> 2016-05-27 20:09:14,785 - INFO - 解析: "[易] #/album?id=3377045" ..... [专辑] Adele => 25
    |-> [曲目] Hello
    |-> [曲目] Send My Love (To Your New Lover)
    |-> [曲目] I Miss You
    |-> [曲目] When We Were Young
    |-> [曲目] Remedy
    |-> [曲目] Water Under The Bridge
    |-> [曲目] River Lea
    |-> [曲目] Love In The Dark
    |-> [曲目] Million Years Ago
    |-> [曲目] All I Ask
    |-> [曲目] Sweetest Devotion
2016-05-27 20:09:14,785 - INFO -  下载任务总数: 11
 3秒后开始下载
2016-05-27 20:09:17,802 - ERROR - Song [id:36841430] cannot be downloaded
2016-05-27 20:09:17,803 - ERROR - Song [id:36871371] cannot be downloaded
2016-05-27 20:09:17,804 - ERROR - Song [id:36841429] cannot be downloaded
2016-05-27 20:09:17,805 - ERROR - Song [id:36871370] cannot be downloaded
2016-05-27 20:09:17,805 - ERROR - Song [id:36871366] cannot be downloaded
2016-05-27 20:09:17,806 - ERROR - Song [id:36871367] cannot be downloaded
2016-05-27 20:09:17,807 - ERROR - Song [id:36841426] cannot be downloaded
2016-05-27 20:09:17,807 - ERROR - Song [id:36841427] cannot be downloaded
2016-05-27 20:09:17,808 - ERROR - Song [id:36871368] cannot be downloaded
2016-05-27 20:09:17,809 - ERROR - Song [id:36841428] cannot be downloaded
2016-05-27 20:09:17,811 - ERROR - Song [id:36871369] cannot be downloaded
2016-05-27 20:13:50,345 - WARNING - [易]无法解析/下载歌曲链接: [Hello]
2016-05-27 20:13:50,346 - INFO - 解析: "[易] #/song?id=36841430" ..... [曲目] Hello
2016-05-27 20:13:50,346 - INFO -  下载任务总数: 1
 3秒后开始下载
2016-05-27 20:13:53,360 - ERROR - Song [id:36841430] cannot be downloaded

**Comment by kobemtl** [comment]
I think there is still a problem when using proxy. 

I often get "ERROR - Song [id:xxxxxxxx] cannot be downloaded" with proxy even i set the thread size to 1. but if I used another python script(wangxi) to get the real download address then download by curl with same proxy. It just works fine. 

Maybe I just ask too much. I will be very appreciated if you can take a look at this issue. anyway thank you so much for the tool.

**Comment by sk1418** [comment]
please give me an song link, that didn't work by you. I can check it out.

**Comment by kobemtl** [comment]
here u go.

http://music.163.com/#/album?id=3377045

**Comment by sk1418** [comment]
The songs in this album have different json format. E.g quality, bitrate are empty. They are important for the later POST parameter encryption. It seems that 163 has changed apis on **some** songs. Can you check your downloaded 1st  song "Hello", what bitrates does it have? also is it ok to share the "wangxi" script? I can check how does this script find out the link for those changed songs.

**Comment by kobemtl** [comment]
sorry it should be wangyi https://github.com/NULL1945/netease_cloud_music_cli

I am not in front of my computer. iwill try later.  

thx again.

**Comment by sk1418** [comment]
Thanks for the link. I 've read the codes how does it fetch the link. zhuaxia used the same way in v2.x. It hardcoded the host, and encrypt the `dfsid`. However this way didn't work any longer since last update. 163 sends the real link via a POST response.  Perhaps they changed back? 

With this php script, I cannot see why the "Hello" song could work. Since there is no `dfsid`  in returned json. I don't have PHP environment, could test with only the single song "Hello", it it works? 

thx...

**Comment by kobemtl** [comment]
Sorry. I was not able to access music.163.com in past few days. And I just had the chance to do a lot of tests today. the script works just fine. But for some particular albums, its not working. very luckily the one we used to test, http://music.163.com/album?id=1515345, is one of it. 

So in general your script works great and I just want to thank you for your work. Sorry for wasting your time. 太謝謝你啦！！！！！

**Comment by kobemtl** [comment]
just realize the song is in 128 instead 320 Kbps. If you have the time, would you mind take a look at it?

Thanks again.

**Comment by sk1418** [comment]
zhuaxia cannot download the bitrates which doesn't exist. Some songs at 163, they don't have 320k quality resources.

**Comment by kobemtl** [comment]
Hmmmm........................ I just did small test. And seems like not that case. 

the test song link I use: http://music.163.com/#/song?id=35847388. As you can see below, it has 320k. 

**# First I used the other php script:**

> ~$ php ~/tmp/netease_cloud_music_cli/netease_cloud_music.php 35847388

> ID: 35847388	Hello
> H:	http://m1.music.126.net/S0g_AwJqybk2JPLR6v0yHA==/3294136840472684.mp3
> M:	http://m1.music.126.net/KqUZylnBHqPQ6K83SRHQHw==/3294136840472685.mp3
> L:	http://m1.music.126.net/h_ZICx_KhDF9wtOtkKrXWA==/3294136840472686.mp3
> 请用此命令下载： curl -o ABC.mp3 http://m1.music.126.net/XXXXX/YYYYY.mp3
> ~$ curl -x proxyhost:port -o Hello.mp3 http://m1.music.126.net/S0g_AwJqybk2JPLR6v0yHA==/3294136840472684.mp3
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 **11.2M**  100 11.2M    0     0   246k      0  0:00:46  0:00:46 --:--:--  247k
> 
> mediainfo Hello.mp3
> General
> Complete name                            : Hello.mp3
> Format                                   : MPEG Audio
> File size                                : 11.3 MiB
> Duration                                 : 4mn 55s
> Overall bit rate mode                    : Constant
> Overall bit rate                         : 320 Kbps
> Writing library                          : LAME3.99.5
> 
> Audio
> Format                                   : MPEG Audio
> Format version                           : Version 1
> Format profile                           : Layer 3
> Mode                                     : Joint stereo
> Duration                                 : 4mn 55s
> Bit rate mode                            : Constant
> Bit rate                                 : 320 Kbps
> Channel(s)                               : 2 channels
> Sampling rate                            : 44.1 KHz
> Compression mode                         : Lossy
> Stream size                              : 11.3 MiB (100%)
> Writing library                          : LAME3.99.5

**# Then I used zhuaxia:**

> ~$ zx http://music.163.com/#/song?id=35847388
> 解析: "[易] #/song?id=35847388" ..... [曲目] Hello
> ==========================================================================================
>  下载任务总数: 1
>  3秒后开始下载
> 
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>   保存目录:[/home/kobe/songs/TMP/] | 线程池:[1]
>  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>                           总进度[1/1]: [#######################################] 100.0% (0kib/s)
>  ===================================================================================================
>  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>   最近1个完成任务:
>  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>  √ Adele_Hello.mp3
>  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>  为成功下载建立历史记录...
>  所有任务都已完成
> (q)退出/(v)查看下载报告/(s)保存下载报告. 请输入 [q/v/s]:q
> 
> mediainfo songs/TMP/Adele_Hello.mp3 
> General
> Complete name                            : songs/TMP/Adele_Hello.mp3
> Format                                   : MPEG Audio
> File size                                : 4.51 MiB
> Duration                                 : 4mn 55s
> Overall bit rate mode                    : Constant
> Overall bit rate                         : 128 Kbps
> Album                                    : Hello
> Track name                               : Hello
> Track name/Position                      : 1
> Performer                                : Adele
> 
> Audio
> Format                                   : MPEG Audio
> Format version                           : Version 1
> Format profile                           : Layer 3
> Mode                                     : Joint stereo
> Mode extension                           : MS Stereo
> Duration                                 : 4mn 56s
> Bit rate mode                            : Constant
> Bit rate                                 : 128 Kbps
> Channel(s)                               : 2 channels
> Sampling rate                            : 44.1 KHz
> Compression mode                         : Lossy
> Stream size                              : 4.51 MiB (100%)
>

**Comment by kobemtl** [comment]
And you are definitely right. The other php script hardcoded the host and not working on most of the songs.

**Comment by sk1418** [comment]
Pls add the -H option and try again.  Check zx -h

**Comment by kobemtl** [comment]
OK, Got you. I tried H option and it works now. I did checked the help. Thought H option only for XIAMI. 

Anyway, Thank you so much!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sk1418** [comment]
it says, -H is for high-Q, however for xiami you need a valid VIP account,
for 163 no special requirement is needed. just -H.
