### ISSUE TITLE
网易灰色链接歌曲不能下载

### ISSUE THREAD

**Issue by S1U** [sk1418/zhuaxia#45]
之前歌曲链接即使是灰色，还是照样能下载的。刚发现，提示无法解析。

参考链接 http://music.163.com/#/song?id=186315，http://music.163.com/#/song?id=108157

**Comment by sk1418** [comment]
@S1U  刚测试了下, 163返回的信息里没有歌曲链接信息. 所以zhuaxia无法下载. 解析是可以的...
而且我挂国内代理, 浏览器也无法播放/下载.. 我想这个目前看没什么办法解决. 至于以前为什么可以, 不清楚了, 也许是163的漏洞吧
不好意思, close了啊.
