### ISSUE TITLE
get_real_id : regex error

### ISSUE THREAD

**Issue by h2597650** [sk1418/zhuaxia#50]
/zhuaxia/xiami.py, line 463
possible_id = re.search(regex , url).group(0) --> possible_id = re.search(regex , url).group(0).strip()
Otherwise possible_id will not be identified.

**Comment by sk1418** [comment]
I had checked after getting the `possible_id`:  

    if re.match('^\d+$', possible_id)....

it would work correctly.

pls provide an example to show that `strip()` is necessary.

**Comment by h2597650** [comment]
http://www.xiami.com/song/1773344106
http://www.xiami.com/song/3673869
http://www.xiami.com/song/3673876
http://www.xiami.com/song/1771589641
http://www.xiami.com/song/1773384009

**Comment by sk1418** [comment]
sorry for the late response.
I tested first two links, zhuaxia can download them smoothly. No error occurred. Have you updated zhuaxia to latest version? (v3.2.0)  check your version by `zx -v`
