### ISSUE TITLE
only fetch 10 song from artist URL even after specify 50

### ISSUE THREAD

**Issue by arifflexter** [sk1418/zhuaxia#51]
I'm editing default.conf to set
download.artist.topsong = 50

even config.py
#here check topx, if the value <= 0, there is no upper-bound 
DOWNLOAD_TOP_SONG    = 50

But in execution it still only download 10 song from each artist URL given via file contain 75 artist URL list.
called with function zx -lif /tmp/filename.txt

on execution
==========================================================================================
 文件包含链接总数: 75
==========================================================================================
[1/75] 解析: "[易] #/artist?id=48161" ..... [艺人热门歌曲] Ariana Grande => 包含10首歌曲.
[2/75] 解析: "[易] #/artist?id=85526" ..... [艺人热门歌曲] Avenged Sevenfold => 包含10首歌曲.
[3/75] 解析: "[易] #/artist?id=46487" ..... [艺人热门歌曲] Adele => 包含10首歌曲.
[4/75] 解析: "[易] #/artist?id=1074089" ..... [艺人热门歌曲] Alessia Cara => 包含10首歌曲.
[5/75] 解析: "[易] #/artist?id=81349" ..... [艺人热门歌曲] The Avett Brothers => 包含10首歌曲.
[6/75] 解析: "[易] #/artist?id=989017" ..... [艺人热门歌曲] Andrew McMahon in the Wilderness => 包含10首歌曲.
[7/75] 解析: "[易] #/artist?id=12107966" ..... [艺人热门歌曲] A Boogie Wit da Hoodie => 包含10首歌曲.

**Comment by arifflexter** [comment]
sure, please update the case if you find something, thank you so much

**Comment by sk1418** [comment]
@arifflexter , I don't know if you have updated to the latest zhuaxia, I just tested with link (adele) (http://music.163.com/#/artist?id=46487)   

no matter `zx -lif  <(echo 'http://music.163.com/#/artist?id=46487')` or `zx -li 'http://music.163.com/#/artist?id=46487'`  **47** Songs were parsed.:


	kent$ (dev|…) zx -lif  <(echo 'http://music.163.com/#/artist?id=46487')
	==========================================================================================
	 文件包含链接总数: 1
	==========================================================================================
	WARNING: [易]歌曲(Million Years Ago (Efe Tekin Remix)) 无法获取128kbps资源,尝试获取低质量资源
	[1/1] 解析: "[易] #/artist?id=46487" ..... [艺人热门歌曲] Adele => 包含50首歌曲.
	==========================================================================================
	WARNING:  启用增量下载, 忽略3首曾下载过的歌曲.
	 下载任务总数: 50-3=47
	 3秒后开始下载
	^C%   

Can you update zhuaxia and double check the same link?

**Comment by arifflexter** [comment]
it's worked like charm now, 40 files due to 10 songs already in history.
Will work for the full list now, thank you so much man, awesome work you have here!
