### ISSUE TITLE
网易云音乐无法下载？

### ISSUE THREAD

**Issue by shubo83** [sk1418/zhuaxia#53]
zx -i 'http://music.163.com/#/playlist?id=726870803'
下载任务总数: 43
 3秒后开始下载
然后下面一排的
ERROR: Song [id:33785948] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:26572039] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:424995312] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:423997619] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:426026290] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:36496637] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:29758178] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:1066422] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:34200871] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:25706371] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:29418848] cannot be downloaded. Filename or dl_link is missing.
ERROR: Song [id:404436963] cannot be downloaded. Filename or dl_link is missing.

请问是由于网易屏蔽了什么吗

**Comment by sk1418** [comment]
周末我找时间看看, 现在不好说. 公司本身有代理, 挂不上国内代理.

**Comment by sk1418** [comment]
@shubo83 
的确网易的json做了调整. 已经进行了相应修复. 你的链接我做了测试, 可以下载了. 我先close这个issue了. 如果你有还有问题, 再reopen吧.

改动已经在bleeding and master branch.

**Comment by shubo83** [comment]
可以了，多谢

**Comment by q2192054** [comment]
我也遇到了这个问题，我所运行的代码就是来自 Master branch ...
已经使用了 -p 来使用代理

**Comment by sk1418** [comment]
@q2192054  这个问题已经解决并且 @shubo83  已经测试确认. 
你的问题可能不是同样的, 如果确认问题存在, 请新开issue并提供测试数据.
