### ISSUE TITLE
虾米音乐 歌曲名称获取有误

### ISSUE THREAD

**Issue by JustZiya** [sk1418/zhuaxia#55]
`zx -H "http://www.xiami.com/collect/352992824" `

下载时发现所有歌曲都只获取到了专辑名称，而不是歌曲的名称。

> Sound	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_Sound.mp3
> Sound	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_Sound.mp3
> 请将手放开	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_请将手放开.mp3
> 惊喜	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_惊喜.mp3
> Sound	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_Sound.mp3
> 不见不散	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_不见不散.mp3
> 不见不散	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_不见不散.mp3
> 不见不散	/home/pi/Downloads/Downloading/喜欢的音乐/Beyond_不见不散.mp3

**Comment by sk1418** [comment]
你下载的是个人收藏, 所以下载好文件的命名格式应该是 `演唱者(or作者)_歌曲名称.mp3` 根据你贴的图, 也正确啊. 当下载个人收藏时, 好像并不解析专辑名称我记得...

**Comment by JustZiya** [comment]
正确的应该是 演唱者(or作者)_歌曲名称 ，但是现在是 演唱者(or作者)_专辑名称。
我随便新建了个歌单，这个看起来更清楚一些。

`http://www.xiami.com/collect/353318512`

里面两首歌

> 无重状态 -- Beyond
> 星期天 -- Beyond

都属于 《不见不散》这张专辑
下载的结果是：

> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 成功下载列表:
> >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 
> 歌曲名  保存路径
> 不见不散        /home/pi/Downloads/Downloading/zx/Beyond_不见不散.mp3
> 不见不散        /home/pi/Downloads/Downloading/zx/Beyond_不见不散.mp3
> (END)

**Comment by sk1418** [comment]
ok 我明白你的意思了, 前面因为list里歌曲过多, 没太理解. 我下班回去看看.公司挂不了国内代理.
另外, 是所有保存的文件名都是错误的还是只有一些(比如你举的两个例子)是错误的?

**Comment by JustZiya** [comment]
嗯，我这里试过的几次都是 所有保存的文件名都是错误的。

是的，最终就是只有一个 Beyond_不见不散.mp3 文件，之前的被覆盖了。

**Comment by sk1418** [comment]
应该是xiami一方在json格式上做了一些调整, 以前曾经有歌曲名称获取失灵的一个bug. 这次可能又是类似情形.  已修复.

请测试一下, 并反馈.

**Comment by JustZiya** [comment]
> zhuaxia (抓虾) 3.2.3

刚刚更新试了一下，并未修复，结果还是一样的
看了下Commits好像只改了版本号忘记提交文件了？
😂

**Comment by sk1418** [comment]
@JustZiya  实在抱歉, 文件是添加了, 只是忘了merge 到 master branch了.  在dev and bleeding branches里已经有了. 我刚刚merge 到了master.
麻烦你再测试一下. 粗心了, 见笑.

**Comment by JustZiya** [comment]
现在没有问题了。已经可以正常抓取，谢谢~
