### ISSUE TITLE
批量下载时，-l 下载歌词 缺失

### ISSUE THREAD

**Issue by shubp** [sk1418/zhuaxia#56]
下载记录明明有10个lrc，但/tmp/test只有一个lrc甚至没有。苦恼中。

**Comment by sk1418** [comment]
你的描述不是一个能reproduce的issue。
这样我没法调试。
请给出链接以及你运行的命令。

**Comment by shubp** [comment]
啊，对不起。因为我打开的是钢琴曲专辑，就没有歌词。再次抱歉。
