### ISSUE TITLE
网易云音乐下载问题

### ISSUE THREAD

**Issue by q2192054** [sk1418/zhuaxia#58]
系统环境

Ubuntu 17.04
Python 2.7.13
zhuaxia 2017-08-20 Version 3.2.3

遇到问题的时的指令

zx -l -H -p  "http://music.163.com/song?id=63650"

运行后提示 
ERROR: Song [id:63650] cannot be downloaded. Filename or dl_link is missing.
但可以下载到歌词

zx -l -H -p  "http://music.163.com/playlist?id=420414554"

运行后卡在

proxy pool:[0] 初始完毕

**Comment by sk1418** [comment]
经测试, 两个连接都可以正常下载, (第二个因为歌曲较多, 56首, 我中断了下载). 你再检查下:

- 如果你是海外IP, 要在配置文件里设置中国代理选项(参见readme)
- 如果是中国IP, 不用设置代理选项
- `-p` 是实验性选项, 因为需要到代理网站抓代理服务器, 不能保证代理服务器的有效性. 一般不用添加.

请你再检查, 测试一下. 你的问题在这里不能重现.
