### ISSUE TITLE
Cannot download songs from XiaMi

### ISSUE THREAD

**Issue by yang-ling** [sk1418/zhuaxia#59]
At first thanks for your great tool!

It worked wonderfully until recent days. I cannot download songs from XiaMi.

URL: http://www.xiami.com/song/376032

Error Message:

    WARNING: [虾] 不登录虾米进行下载, 虾米资源质量为128kbps.
    ERROR: [虾]无法解析/下载歌曲链接: [http://www.xiami.com/song/376032]
    Traceback (most recent call last):
      File "/usr/bin/zx", line 122, in <module>
        commander.shall_I_begin(option)
      File "/usr/lib/python2.7/site-packages/zhuaxia/commander.py", line 68, in
    shall_I_begin
        from_url_xm(xiami_obj, option.inUrl)
      File "/usr/lib/python2.7/site-packages/zhuaxia/commander.py", line 176, in
    from_url_xm
        song = xm.XiamiSong(xm_obj, url=url)
      File "/usr/lib/python2.7/site-packages/zhuaxia/xiami.py", line 64, in
    __init__
        jsong = self.handler.read_link(url_song %
    self.song_id).json()['data']['trackList'][0]
      File "/usr/lib/python2.7/site-packages/requests/models.py", line 892, in
    json
        return complexjson.loads(self.text, **kwargs)
      File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

zhuaxia is the latest.

Maybe XiaMi changes API again?

**Comment by sk1418** [comment]
@yang-ling 
I am gonna check it when I am home, here I cannot reach xiami via chinese proxy. but can you check if you open that song in browser, can you play that song? since someone asked me per mail just a couple days ago, with same error msg. I checked that song he mentioned in mail, the song is not available on xiami. you can check if it is the same case. If the song is not able to be played on xiami website (via browser) zhuaxia cannot download it either.

**Comment by yang-ling** [comment]
@sk1418 Hi, sorry for late reply. I can play the song by browser. Actually I can download it by a chrome plugin.  [Video Download Heler](https://chrome.google.com/webstore/detail/video-downloadhelper/lmjnegcaeklhafolokijcfjliaokphfk)
Hope it help.

**Comment by sk1418** [comment]
@yang-ling  problem fixed.  local tested with your link, worked. pls test and feedback. Thx. 
Changes are already in master branch.

**Comment by yang-ling** [comment]
@sk1418 It works! I tried to download several songs and one album. All of them are successfully downloaded.

Thanks again for your work.
