### ISSUE TITLE
how can I use it on Windows?

### ISSUE THREAD

**Issue by JohnWins** [sk1418/zhuaxia#61]
Hi, 
I am not sure how can I use it on windows after installed correctly?

**Comment by sk1418** [comment]
It was written in python, basically, it should work on windows. however, the terminal stuff(progress bar etc.) may not work. I remember there was someone did some changes on zhuaxia to make it work on windows. You can check the old issues.

How to make it work on a windows box is not in my focus. I don't have a windows machine and don't have much experience with Windows either. It is too expensive for me to maintain or test zhuaxia on windows. so, sorry about that.
